"""
22/02/2022
Author: Virginia Listanti
Reviewed 20/11/2022

This script purpose is to analyse data generated by IF_experiment_cuda tests
In this script we will analyse optimal spectrogram parameters (only for standard normalisation)
"""

import SignalProc
import IF as IFreq
import numpy as np
import matplotlib.pyplot as plt
import os
import csv
import ast

# signal type we are analysing
# signal_id = 'pure_tone'
# signal_id = 'linear_upchirp'
# signal_id = 'linear_downchirp'
# signal_id = 'exponential_downchirp'
signal_id = 'exponential_upchirp'

#analysis for test folder
test_result_dir = "C:\\Users\\Virginia\\Documents\\Work\\IF_extraction\\Test_Results"
test_analysis_dir = "C:\\Users\\Virginia\\Documents\\Work\\IF_extraction\\Results analysis\\" \
                    "General_parameters_comparison"

# Spectrogram parameters
win_list = {'256': 0, '512': 0, '1024': 0, '2048': 0}
incr_list = {'25': 0, '51': 0, '64': 0, '102': 0, '128': 0, '192': 0, '204': 0, '230': 0, '256': 0, '384': 0, '460': 0,
             '512': 0, '768': 0, '921': 0, '512': 0, '1024': 0, '1536': 0, '1843': 0}
win_type_list = {'Hann': 0, 'Parzen': 0, 'Welch': 0, 'Hamming': 0, 'Blackman': 0}

# If Extraction parameters
alpha_list = {'0.0': 0, '0.5': 0, '1.0': 0, '2.5': 0, '5.0': 0, '7.5': 0, '10.0': 0}
beta_list = {'0.0': 0, '0.5': 0, '1.0': 0, '2.5': 0, '5.0': 0, '7.5': 0, '10.0': 0}

# mel bins options
mel_bins = {'None': 0, '64': 0, '128': 0, '256': 0}  # only power of 2

#test list

test_list = ['Test_0', 'Test_1', 'Test_2', 'Test_3', 'Test_4', 'Test_5', 'Test_30', 'Test_31', 'Test_32', 'Test_33',
             'Test_34', 'Test_35', 'Test_60', 'Test_61', 'Test_62', 'Test_63', 'Test_64', 'Test_65', 'Test_90',
             'Test_91', 'Test_92', 'Test_93', 'Test_94', 'Test_95', 'Test_120', 'Test_121', 'Test_122', 'Test_123',
             'Test_124', 'Test_125', 'Test_150', 'Test_151', 'Test_152', 'Test_153', 'Test_154', 'Test_155']

#cunting tests
n=0
for test_id in test_list:
    #open TFR_inf file
    #save folder path
    folder_path = test_result_dir+'\\'+test_id

    if not signal_id in os.listdir(folder_path):
        #if not test for signal_id continue
        continue

    #open TFR_info_path
    dictionary_path = folder_path +'\\'+signal_id+'\\'+'Optimal_parameters.txt'

    with open(dictionary_path) as f:
        data_param = f.read()

    #turn raw data into dictionary
    opt_param = ast.literal_eval(data_param)

    win_list[str(opt_param['win_len'])] += 1
    incr_list[str(opt_param['hop'])] += 1
    win_type_list[str(opt_param['window_type'])] += 1
    mel_bins[str(opt_param['mel_num'])] += 1
    alpha_list[str(opt_param['alpha'])] += 1
    beta_list[str(opt_param['beta'])] += 1

    n +=1


    del opt_param


#save plots
save_dir = "C:\\Users\\Virginia\\Documents\\Work\\Thesis_images\\Chapter_3\\Optimal_parameters"
fig_name = save_dir + '\\'+signal_id +'_optimal_parametes.jpg'
#plt.rcParams["figure.autolayout"] = True

fig, ax = plt.subplots(3, 2, figsize=(10,10))


bar_width = 0.2

index1 = np.arange(len(win_list))
ax[0, 0].set_title('Win length',fontsize=12)
ax[0, 0].bar(index1, win_list.values(), color='midnightblue')
ax[0, 0].set_xticks(index1, labels= win_list.keys(), fontsize=10)
ax[0, 0].tick_params(axis='y', labelsize=10)
#ax[0, 0].set_yticks(fontsize=20)
#ax[0].set_xticks(index1)

index2 = np.arange(len(incr_list))
ax[0, 1].set_title('Incr length',fontsize= 12)
ax[0, 1].bar(index2, incr_list.values(), color='darkslateblue')
ax[0, 1].set_xticks(index2, labels=incr_list.keys(), fontsize=6)
ax[0, 1].tick_params(axis='y', labelsize=10)

index3 = np.arange(len(win_type_list))
ax[1, 0].set_title('Win type',fontsize= 12)
ax[1, 0].bar(index3, win_type_list.values(), color='indigo')
ax[1, 0].set_xticks(index3, labels= win_type_list.keys(), fontsize=10)
ax[1, 0].tick_params(axis='y', labelsize=10)
#ax[0].set_xticks(index1)

index4 = np.arange(len(mel_bins))
ax[1, 1].set_title('mel bins',fontsize= 12)
ax[1, 1].bar(index4, mel_bins.values(), color='rebeccapurple')
ax[1, 1].set_xticks(index4, labels=mel_bins.keys(), fontsize=10)
ax[1, 1].tick_params(axis='y', labelsize=10)

index5 = np.arange(len(alpha_list))
ax[2, 0].set_title('Alpha',fontsize= 12)
ax[2, 0].bar(index5, alpha_list.values(), color='darkorchid')
ax[2, 0].set_xticks(index5, labels= alpha_list.keys(), fontsize=10)
ax[2, 0].tick_params(axis='y', labelsize=10)
#ax[0].set_xticks(index1)

index6 = np.arange(len(beta_list))
ax[2, 1].set_title('Beta',fontsize= 12)
ax[2, 1].bar(index6, beta_list.values(), color='darkmagenta')
ax[2, 1].set_xticks(index6, labels=beta_list.keys(), fontsize=10)
ax[2, 1].tick_params(axis='y', labelsize=10)

fig.suptitle(signal_id, fontsize=20)
fig.tight_layout()
plt.savefig(fig_name, dpi =200)







