"""
15/02/2022
Author: Virginia Listanti

This script purpose is to analyse data generated by IF_experiment_cuda tests
"""

import SignalProc
import IF as IFreq
import numpy as np
import matplotlib.pyplot as plt
import os
import csv


#analysis for test folder
test_result_dir = "C:\\Users\\Virginia\\Documents\\Work\\IF_extraction\\Test_Results"
test_id = "Test_0"


#read .csv files