#!/usr/bin/env python3
"""
Evaluate BirdNET on test datasets and compare with ground truth.

This script provides external model evaluation using BirdNET as a baseline.
NOTE: This script requires audio files in the test datasets, which are not
      generated by the standard data pipeline. It's a standalone utility
      for comparing BirdNET performance.

Usage:
    # Install BirdNET first:
    pip install birdnetlib

    # Run BirdNET evaluation on test sets:
    python scripts/evaluate_birdnet.py \
        /path/to/test_set1 /path/to/test_set2 \
        --output results/birdnet_eval
        
    Note: Test datasets must have audio/ subfolders with .wav files
"""

import csv
import os
import sys
import json
import argparse
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from datetime import datetime
from collections import defaultdict
import subprocess

try:
    from birdnetlib import Recording
    from birdnetlib.analyzer import Analyzer
except ImportError:
    print("ERROR: birdnetlib not installed!")
    print("Install with: pip install birdnetlib")
    sys.exit(1)


# Keys match the common-name labels used in labels.json (lowercased)
SPECIES_MAPPING = {
    'nezfan1':      'Fantail',
    'silver3':      'Silvereye',
    'comcha':       'Chaffinch',
    'tui/bellbird': 'Tui/Bellbird',  # combined class in the dataset
    'eurbla':       'Blackbird',
    'morepo2':      'Morepork',
    'gryger1':      'Grey Warbler',
    'nezkak1':      'Kaka',
    'tomtit1':      'Tomtit',
}

SPECIES_SCIENTIFIC = {
    'nezfan1':      'Rhipidura fuliginosa',
    'silver3':      'Zosterops lateralis',
    'comcha':       'Fringilla coelebs',
    'tui/bellbird': 'Prosthemadera novaeseelandiae / Anthornis melanura',
    'eurbla':       'Turdus merula',
    'morepo2':      'Ninox novaeseelandiae',
    'gryger1':      'Gerygone igata',
    'nezkak1':      'Nestor meridionalis',
    'tomtit1':      'Petroica macrocephala',
}

# BirdNET scientific name → dataset species code.
# Both Tui and Bellbird map to the combined 'tui/bellbird' class.
SCIENTIFIC_TO_CODE = {
    'Rhipidura fuliginosa':          'nezfan1',
    'Zosterops lateralis':           'silver3',
    'Fringilla coelebs':             'comcha',
    'Prosthemadera novaeseelandiae': 'tui/bellbird',
    'Anthornis melanura':            'tui/bellbird',
    'Turdus merula':                 'eurbla',
    'Ninox novaeseelandiae':         'morepo2',
    'Gerygone igata':                'gryger1',
    'Nestor meridionalis':           'nezkak1',
    'Petroica macrocephala':         'tomtit1',
}

# Reverse map: lowercase common name → species code (e.g. 'silvereye' → 'silver3')
COMMON_NAME_TO_CODE = {v.lower(): k for k, v in SPECIES_MAPPING.items()}


def _common_name_col(common_name):
    """Normalise a BirdNET common name to a safe CSV column identifier."""
    return common_name.strip().lower().replace(' ', '_').replace('/', '_').replace("'", '')


def label_to_codes(label):
    label = label.strip().lower()
    label = label.replace(' / ', '/').replace('/ ', '/').replace(' /', '/')

    code = COMMON_NAME_TO_CODE.get(label)
    if code:
        return {code}

    codes = set()
    for part in label.split('/'):
        code = COMMON_NAME_TO_CODE.get(part.strip())
        if code:
            codes.add(code)
    return codes


class BirdNETEvaluator:
    def __init__(self, output_folder, min_confidence=0.1, latitude=-41.2865, longitude=174.7762):
        self.output_folder = Path(output_folder)
        self.output_folder.mkdir(parents=True, exist_ok=True)
        self.min_confidence = min_confidence
        self.latitude = latitude
        self.longitude = longitude
        
        print(f"\nInitializing BirdNET Analyzer...")
        print(f"Location: {latitude}, {longitude} (New Zealand)")
        print(f"Min confidence: {min_confidence}")
        
        self.analyzer = Analyzer()
        
        self.results = []
        self.species_codes = list(SPECIES_MAPPING.keys())
        self.species_names = [SPECIES_MAPPING[code] for code in self.species_codes]
        
        print(f"✓ BirdNET Analyzer ready")
        print(f"\nTarget species ({len(self.species_codes)}):")
        for code in self.species_codes:
            name = SPECIES_MAPPING[code]
            sci = SPECIES_SCIENTIFIC[code]
            print(f"  {code:12s} → {name:12s} ({sci})")
    

    
    def predict_file(self, wav_path):
        from birdnetlib.exceptions import AudioFormatError
        recording = Recording(
            self.analyzer,
            str(wav_path),
            lat=self.latitude,
            lon=self.longitude,
            min_conf=self.min_confidence
        )

        try:
            recording.analyze()
        except (AudioFormatError, Exception) as e:
            print(f"  WARNING: skipping {Path(wav_path).name} — {e}")
            return []

        detections = []
        for detection in recording.detections:
            detections.append({
                'common_name': detection['common_name'],
                'scientific_name': detection['scientific_name'],
                'confidence': detection['confidence'],
                'start_time': detection['start_time'],
                'end_time': detection['end_time']
            })

        return detections
    
    def get_top_prediction(self, detections):
        if not detections:
            return None, 0.0
        
        best = max(detections, key=lambda x: x['confidence'])
        return best['scientific_name'], best['confidence']
    
    def find_matching_species(self, scientific_name):
        return SCIENTIFIC_TO_CODE.get(scientific_name, None)
    
    def evaluate_folder(self, test_folder, dataset_name):
        print(f"\n{'='*60}")
        print(f"Evaluating: {dataset_name}")
        print(f"Folder: {test_folder}")
        print(f"{'='*60}")

        test_path = Path(test_folder)

        if not test_path.exists():
            print(f"ERROR: Folder not found: {test_folder}")
            return None

        labels_path = test_path / 'labels.json'
        if not labels_path.exists():
            print(f"ERROR: No labels.json found")
            return None

        audio_path = test_path / 'audio'
        if not audio_path.exists() or not audio_path.is_dir():
            print(f"ERROR: No audio/ subfolder found")
            print(f"Make sure you used --with-audio when creating the dataset")
            return None

        with open(labels_path, 'r') as f:
            labels_data = json.load(f)

        files = labels_data.get('files', [])
        if not files:
            print(f"ERROR: No files found in labels.json")
            return None

        # Build test-set species codes dynamically from labels.json
        test_codes = set()
        for item in files:
            for label in item.get('class_names', []):
                test_codes.update(label_to_codes(label))
        test_codes = sorted(test_codes)

        # Only score over codes that BirdNET can actually predict
        valid_codes = {code for code in test_codes
                       if any(c == code for c in SCIENTIFIC_TO_CODE.values())}
        missing_codes = set(test_codes) - valid_codes
        if missing_codes:
            print(f"  WARNING: {len(missing_codes)} test-set species have no BirdNET mapping: {sorted(missing_codes)}")
        print(f"  Test-set species: {test_codes}")
        print(f"  Scoring over {len(valid_codes)}/{len(test_codes)} species")
        print(f"  {len(files)} files in dataset")

        file_results = []
        raw_score_records = []
        birdnet_species_seen = set()

        # Mapping from BirdNET code (e.g. 'nezfan1') to dataset class name (e.g. 'fantail')
        code_to_dataset_label = {code: name.lower() for code, name in SPECIES_MAPPING.items()}
        all_dataset_labels = sorted(set(code_to_dataset_label.values()))

        print(f"\nRunning BirdNET predictions...")
        for i, file_info in enumerate(files, 1):
            npy_filename = file_info['filename']
            wav_filename = npy_filename.replace('.npy', '.wav')
            wav_file = audio_path / wav_filename

            if not wav_file.exists():
                continue

            # Ground truth: set of valid codes from this sample's class_names
            gt_codes = set()
            for label in file_info.get('class_names', []):
                for code in label_to_codes(label):
                    if code in valid_codes:
                        gt_codes.add(code)

            detections = self.predict_file(wav_file)

            # Collect max confidence per label (raw scores for threshold tuning).
            # NZ target species → dataset common-name label (e.g. 'fantail').
            # All other BirdNET species → normalised common-name column.
            max_conf = defaultdict(float)

            # Predicted codes: all detections at or above min_confidence that map to a valid code
            pred_codes = set()
            for det in detections:
                birdnet_species_seen.add(det['scientific_name'])
                conf = det['confidence']
                code = SCIENTIFIC_TO_CODE.get(det['scientific_name'])
                if code:
                    dataset_label = code_to_dataset_label.get(code)
                    if dataset_label:
                        max_conf[dataset_label] = max(max_conf[dataset_label], conf)
                    if conf >= self.min_confidence and code in valid_codes:
                        pred_codes.add(code)
                else:
                    # Non-target species: record score under normalised common name
                    col = _common_name_col(det['common_name'])
                    max_conf[col] = max(max_conf[col], conf)

            correct = pred_codes == gt_codes

            if i % 20 == 0 or i == len(files):
                status = '\u2713' if correct else '\u2717'
                print(f"  [{i}/{len(files)}] {status} GT:{sorted(gt_codes)} Pred:{sorted(pred_codes)}")

            file_results.append({
                'filename': wav_filename,
                'gt_codes': sorted(gt_codes),
                'pred_codes': sorted(pred_codes),
                'correct': correct,
            })

            # Raw score record: npy filename + per-class max confidence (0 if not detected).
            # Store ALL detected labels (NZ target + non-target) so that plot_results.py
            # standard mode can penalise BirdNET for spurious non-NZ predictions.
            gt_labels = [lbl for lbl in all_dataset_labels
                         if any(c in valid_codes for c in label_to_codes(lbl)
                                if c in gt_codes)]
            raw_rec = {'filename': npy_filename, 'gt_classes': gt_labels}
            # NZ target species (fill 0 when not detected)
            for lbl in all_dataset_labels:
                raw_rec[lbl] = max_conf.get(lbl, 0.0)
            # Non-target species (only entries actually detected, rest filled later)
            for col, score in max_conf.items():
                if col not in raw_rec:
                    raw_rec[col] = score
            raw_score_records.append(raw_rec)

        n = len(file_results)
        if n == 0:
            print("  No files evaluated.")
            return None

        n_correct = sum(r['correct'] for r in file_results)
        accuracy = 100.0 * n_correct / n

        labelled = [r for r in file_results if r['gt_codes']]
        n_labelled = len(labelled)
        n_labelled_correct = sum(r['correct'] for r in labelled)
        accuracy_labelled = 100.0 * n_labelled_correct / n_labelled if n_labelled else float('nan')

        background = [r for r in file_results if not r['gt_codes']]
        n_background = len(background)
        n_background_correct = sum(r['correct'] for r in background)
        accuracy_background = 100.0 * n_background_correct / n_background if n_background else float('nan')

        print(f"\n  Accuracy (all):      {n_correct}/{n} = {accuracy:.1f}%")
        print(f"  Accuracy (labelled): {n_labelled_correct}/{n_labelled} = {accuracy_labelled:.1f}%")
        print(f"  Accuracy (background): {n_background_correct}/{n_background} = {accuracy_background:.1f}%")
        print(f"  BirdNET detected {len(birdnet_species_seen)} unique species")
        print(f"{'='*60}")

        # Per-species stats (for plots)
        species_stats = defaultdict(lambda: {'correct': 0, 'total': 0})
        for r in file_results:
            for code in r['gt_codes']:
                species_stats[code]['total'] += 1
                if r['correct']:
                    species_stats[code]['correct'] += 1

        result = {
            'dataset_name': dataset_name,
            'test_folder': str(test_folder),
            'num_files': n,
            'num_correct': n_correct,
            'accuracy': accuracy,
            'accuracy_labelled': accuracy_labelled,
            'accuracy_background': accuracy_background,
            'num_labelled': n_labelled,
            'num_background': n_background,
            'file_results': file_results,
            'species_stats': {k: dict(v) for k, v in species_stats.items()},
            'birdnet_species': sorted(birdnet_species_seen),
            'raw_score_records': raw_score_records,
            'dataset_class_names': all_dataset_labels,
        }

        self.results.append(result)
        return result

    def generate_confusion_matrix(self, result):
        """Plot a single-label confusion matrix using only unambiguous (single-species) samples."""
        print(f"\nGenerating confusion matrix for {result['dataset_name']}...")

        # Collect all species codes seen across this result
        all_codes = sorted({code for r in result['file_results']
                            for code in r['gt_codes'] + r['pred_codes']})
        if not all_codes:
            print("  No species found, skipping confusion matrix.")
            return

        codes_with_none = all_codes + ['none']
        n = len(codes_with_none)
        cm = np.zeros((n, n), dtype=int)

        for r in result['file_results']:
            gt = r['gt_codes']
            pred = r['pred_codes']
            # Only include unambiguous single-label samples for a clean CM
            if len(gt) != 1:
                continue
            g_idx = codes_with_none.index(gt[0])
            p_idx = codes_with_none.index(pred[0]) if len(pred) == 1 and pred[0] in codes_with_none else codes_with_none.index('none')
            cm[g_idx, p_idx] += 1

        labels = [SPECIES_MAPPING.get(c, c) for c in codes_with_none]
        fig, ax = plt.subplots(figsize=(max(8, n * 0.9), max(6, n * 0.8)))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                    xticklabels=labels, yticklabels=labels,
                    ax=ax, cbar_kws={'label': 'Count'})
        ax.set_xlabel('Predicted', fontsize=12, fontweight='bold')
        ax.set_ylabel('Ground Truth', fontsize=12, fontweight='bold')
        ax.set_title(f'Confusion Matrix - {result["dataset_name"]}\nBirdNET Evaluation (single-label samples only)',
                     fontsize=13, fontweight='bold', pad=15)
        plt.tight_layout()
        clean_name = result["dataset_name"].lower().replace("/", "_").replace(" ", "_")
        plot_path = self.output_folder / f'confusion_matrix_{clean_name}.png'
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')
        print(f"  Saved to: {plot_path}")
        plt.close()

    def generate_per_species_accuracy(self):
        print(f"\nGenerating per-species accuracy plot...")

        # Aggregate species_stats across all evaluated datasets
        species_stats = defaultdict(lambda: {'correct': 0, 'total': 0})
        for result in self.results:
            for code, stats in result.get('species_stats', {}).items():
                species_stats[code]['correct'] += stats['correct']
                species_stats[code]['total'] += stats['total']

        all_codes = sorted(species_stats.keys())
        species = [SPECIES_MAPPING.get(c, c) for c in all_codes]
        accuracies = []
        counts = []

        for code in all_codes:
            total = species_stats[code]['total']
            correct = species_stats[code]['correct']
            accuracies.append(100.0 * correct / total if total else 0.0)
            counts.append(total)

        if not all_codes:
            print("  No species data, skipping plot.")
            return

        fig, ax = plt.subplots(figsize=(max(10, len(all_codes) * 0.9), 6))
        bars = ax.bar(range(len(species)), accuracies, color='steelblue', alpha=0.8)

        for i, (bar, count) in enumerate(zip(bars, counts)):
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height + 1,
                    f'{height:.1f}%\n(n={count})',
                    ha='center', va='bottom', fontsize=9)
        
        ax.set_ylabel('Accuracy (%)', fontsize=12, fontweight='bold')
        ax.set_xlabel('Species', fontsize=12, fontweight='bold')
        ax.set_title('BirdNET Per-Species Accuracy', fontsize=14, fontweight='bold', pad=15)
        ax.set_xticks(range(len(species)))
        ax.set_xticklabels(species, rotation=45, ha='right')
        ax.set_ylim(0, 110)
        ax.grid(axis='y', alpha=0.3)
        
        plt.tight_layout()
        
        plot_path = self.output_folder / 'per_species_accuracy.png'
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')
        print(f"  Saved to: {plot_path}")
        plt.close()
    
    def generate_dataset_comparison(self):
        print(f"\nGenerating dataset comparison plot...")
        
        dataset_names = [r['dataset_name'] for r in self.results]
        accuracies = [r['accuracy'] for r in self.results]
        counts = [r['num_files'] for r in self.results]
        
        fig, ax = plt.subplots(figsize=(10, 6))
        
        bars = ax.bar(range(len(dataset_names)), accuracies, color='lightcoral', alpha=0.8)
        
        for i, (bar, count) in enumerate(zip(bars, counts)):
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height + 1,
                    f'{height:.1f}%\n(n={count})',
                    ha='center', va='bottom', fontsize=10)
        
        ax.set_ylabel('Accuracy (%)', fontsize=12, fontweight='bold')
        ax.set_xlabel('Dataset', fontsize=12, fontweight='bold')
        ax.set_title('BirdNET Accuracy by Dataset', fontsize=14, fontweight='bold', pad=15)
        ax.set_xticks(range(len(dataset_names)))
        ax.set_xticklabels(dataset_names, rotation=45, ha='right')
        ax.set_ylim(0, 110)
        ax.grid(axis='y', alpha=0.3)
        
        plt.tight_layout()
        
        plot_path = self.output_folder / 'dataset_comparison.png'
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')
        print(f"  Saved to: {plot_path}")
        plt.close()
    
    def generate_birdnet_species_report(self):
        print(f"\nGenerating BirdNET species report...")
        
        all_species = set()
        for result in self.results:
            all_species.update(result.get('birdnet_species', []))
        
        report_path = self.output_folder / 'birdnet_species_detected.txt'
        
        with open(report_path, 'w') as f:
            f.write("BirdNET Species Detection Report\n")
            f.write("="*60 + "\n\n")
            
            f.write("Target Species (Ground Truth):\n")
            f.write("-"*60 + "\n")
            for code in self.species_codes:
                name = SPECIES_MAPPING[code]
                sci = SPECIES_SCIENTIFIC[code]
                f.write(f"  {code:12s} → {name:12s} ({sci})\n")
            f.write("\n")
            
            f.write(f"BirdNET Detected {len(all_species)} Unique Species:\n")
            f.write("-"*60 + "\n")
            for i, species in enumerate(sorted(all_species), 1):
                matched = self.find_matching_species(species)
                if matched:
                    f.write(f"  {i:3d}. {species:40s} ✓ MATCH → {matched}\n")
                else:
                    f.write(f"  {i:3d}. {species:40s}\n")
            f.write("\n")
            
            f.write("Target Species Coverage:\n")
            f.write("-"*60 + "\n")
            for code in self.species_codes:
                sci = SPECIES_SCIENTIFIC[code]
                if sci in all_species:
                    f.write(f"  ✓ {code:12s} ({sci:40s}) - DETECTED\n")
                else:
                    f.write(f"  ✗ {code:12s} ({sci:40s}) - NOT DETECTED\n")
            f.write("\n")
        
        print(f"  Saved to: {report_path}")
        
        with open(report_path, 'r') as f:
            print(f"\n{f.read()}")
    
    def save_results(self):
        print(f"\nSaving detailed results...")
        
        results_dict = {
            'timestamp': datetime.now().isoformat(),
            'min_confidence': self.min_confidence,
            'location': {
                'latitude': self.latitude,
                'longitude': self.longitude
            },
            'target_species': {
                code: {
                    'common_name': SPECIES_MAPPING[code],
                    'scientific_name': SPECIES_SCIENTIFIC[code]
                }
                for code in self.species_codes
            },
            'results': self.results
        }
        
        json_path = self.output_folder / 'birdnet_results.json'
        with open(json_path, 'w') as f:
            json.dump(results_dict, f, indent=2)
        
        print(f"  Saved to: {json_path}")
    
    def generate_summary_report(self):
        print(f"\nGenerating summary report...")
        
        report_path = self.output_folder / 'summary_report.txt'
        
        with open(report_path, 'w') as f:
            f.write("BirdNET Evaluation Summary\n")
            f.write("="*60 + "\n")
            f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Min Confidence: {self.min_confidence}\n")
            f.write(f"Location: {self.latitude}, {self.longitude}\n")
            f.write("\n")
            
            f.write("Target Species:\n")
            f.write("-"*60 + "\n")
            for code in self.species_codes:
                name = SPECIES_MAPPING[code]
                sci = SPECIES_SCIENTIFIC[code]
                f.write(f"  {code:12s} → {name:12s} ({sci})\n")
            f.write("\n")
            
            f.write("Overall Results:\n")
            f.write("-"*60 + "\n")
            total_files = sum(r['num_files'] for r in self.results)
            total_correct = sum(r['num_correct'] for r in self.results)
            overall_acc = 100.0 * total_correct / total_files if total_files > 0 else 0.0
            
            f.write(f"  Total files: {total_files}\n")
            f.write(f"  Total correct: {total_correct}\n")
            f.write(f"  Overall accuracy: {overall_acc:.2f}%\n")
            f.write("\n")
            
            f.write("Per-Dataset Results:\n")
            f.write("-"*60 + "\n")
            for result in self.results:
                f.write(f"  {result['dataset_name']}:\n")
                f.write(f"    Files: {result['num_files']}\n")
                f.write(f"    Correct: {result['num_correct']}\n")
                f.write(f"    Accuracy: {result['accuracy']:.2f}%\n")
                f.write("\n")
            
            f.write("Per-Species Accuracy:\n")
            f.write("-"*60 + "\n")
            species_stats = defaultdict(lambda: {'correct': 0, 'total': 0})
            for result in self.results:
                for code, stats in result.get('species_stats', {}).items():
                    species_stats[code]['total'] += stats['total']
                    species_stats[code]['correct'] += stats['correct']

            all_codes = sorted(species_stats.keys()) or sorted(SPECIES_MAPPING.keys())
            for code in all_codes:
                name = SPECIES_MAPPING.get(code, code)
                if species_stats[code]['total'] > 0:
                    acc = 100.0 * species_stats[code]['correct'] / species_stats[code]['total']
                    f.write(f"  {name:20s}: {acc:6.2f}% ({species_stats[code]['correct']}/{species_stats[code]['total']})\n")
                else:
                    f.write(f"  {name:20s}: No samples\n")
        
        print(f"  Saved to: {report_path}")
        
        with open(report_path, 'r') as f:
            print(f"\n{f.read()}")
    
    def run(self, test_folders):
        for test_folder in test_folders:
            # Use parent folder name (e.g. 'avianz_split') — same convention as evaluate_kaytoo.py
            p = Path(test_folder).resolve()
            dataset_name = p.parent.name
            self.evaluate_folder(test_folder, dataset_name)

        if len(self.results) > 0:
            # Write result.json so analyze_all_results.py picks this up
            result_json = {
                'name': self.output_folder.name,
                'type': 'pretrained',
                'model': 'birdnet',
                'seed': 0,
                'status': 'completed',
            }
            if len(self.results) >= 1:
                result_json['test1_name'] = self.results[0]['dataset_name']
                result_json['test1_acc'] = self.results[0]['accuracy']
                result_json['test1_acc_labelled'] = self.results[0].get('accuracy_labelled', float('nan'))
                result_json['test1_acc_background'] = self.results[0].get('accuracy_background', float('nan'))
            if len(self.results) >= 2:
                result_json['test2_name'] = self.results[1]['dataset_name']
                result_json['test2_acc'] = self.results[1]['accuracy']
                result_json['test2_acc_labelled'] = self.results[1].get('accuracy_labelled', float('nan'))
                result_json['test2_acc_background'] = self.results[1].get('accuracy_background', float('nan'))
            with open(self.output_folder / 'result.json', 'w') as f:
                json.dump(result_json, f, indent=2)
            print(f"\nSaved result.json to {self.output_folder / 'result.json'}")

            # Save per-split raw score CSVs including ground-truth columns
            # (true_CLASSNAME) so tune_thresholds.py can run locally.
            for result in self.results:
                raw_records = result.get('raw_score_records', [])
                if not raw_records:
                    continue
                split_name = result['dataset_name']
                csv_path = self.output_folder / f'predictions_{split_name}.csv'
                # Build column list from the union of all records (non-target species
                # may only appear in some records).
                _skip = {'filename', 'gt_codes', 'gt_classes', 'pred_codes', 'correct'}
                class_cols = sorted({c for rec in raw_records for c in rec if c not in _skip})
                # Fill any missing columns with 0 so every record is complete.
                for rec in raw_records:
                    for c in class_cols:
                        if c not in rec:
                            rec[c] = 0.0
                with open(csv_path, 'w', newline='') as f:
                    writer = csv.writer(f)
                    writer.writerow(['filename'] + class_cols + [f'true_{c}' for c in class_cols])
                    for rec in raw_records:
                        gt_set = set(rec.get('gt_classes', []))
                        writer.writerow(
                            [rec['filename']]
                            + [f"{rec.get(c, 0.0):.6f}" for c in class_cols]
                            + [int(c in gt_set) for c in class_cols]
                        )
                print(f"Saved {len(raw_records)} raw score rows → {csv_path.name}")

            self.generate_birdnet_species_report()

            for result in self.results:
                self.generate_confusion_matrix(result)

            if len(self.results) > 1:
                self.generate_dataset_comparison()

            self.generate_per_species_accuracy()
            self.save_results()
            self.generate_summary_report()

            print(f"\n{'='*60}")
            print(f"✓ BirdNET evaluation complete!")
            print(f"  Results saved to: {self.output_folder}")
            print(f"{'='*60}")


def main():
    parser = argparse.ArgumentParser(
        description='Evaluate BirdNET on test datasets with audio files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Create datasets with audio:
  python data_loader.py avianz /raw/joe_mo /data/joe_mo --with-audio
  python split_dataset.py /data/joe_mo /data/joe_mo_split
  
  # Evaluate BirdNET on test sets:
  python evaluate_birdnet.py \
      /data/joe_mo_split/test /data/doc_split/test \
      --output results/birdnet_eval
        """
    )
    
    parser.add_argument('test_folders', nargs='+',
                       help='Test folders with audio/ subfolders (created with --with-audio)')
    parser.add_argument('--output', default='results/birdnet_evaluation',
                       help='Output folder (default: results/birdnet_evaluation)')
    parser.add_argument('--min-confidence', type=float, default=0.1,
                       help='Minimum BirdNET confidence threshold (default: 0.1)')
    parser.add_argument('--latitude', type=float, default=-41.2865,
                       help='Latitude for BirdNET (default: -41.2865, Wellington NZ)')
    parser.add_argument('--longitude', type=float, default=174.7762,
                       help='Longitude for BirdNET (default: 174.7762, Wellington NZ)')
    
    args = parser.parse_args()
    
    evaluator = BirdNETEvaluator(
        output_folder=args.output,
        min_confidence=args.min_confidence,
        latitude=args.latitude,
        longitude=args.longitude
    )
    
    evaluator.run(test_folders=args.test_folders)


if __name__ == '__main__':
    main()
